# normally used in the Scripts section of a digital asset as a PythonModule
# this script takes a directory path, a filename, and associated external
# renderer materials, and writes USD PBR(USDPreviewSurface) information 
# write_preview_shading() is implemented in such a way that it works nicely
# in a usd rop post script, you likely use set_usd_filename() as a callback 
# on a HDA button, write_arkit_usdz() writes out a usdz and a layered usda
# using the previous _shade and _geo generated by the ROP and write_preview_shading()
# it fits well as a pre/post script in a Shell ROP attached to a Prepost ROP

import os, sys, ctypes, string, getopt, glob, json
from pxr import Usd, UsdGeom, UsdShade, Sdf, Gf, UsdUtils

import hou
from arnold import *

import htoa
from htoa.universe import HaUniverse
from htoa.node.node import pullHouParms, houdiniParmGet, arnoldParmSet
from htoa.node.parms import *
    
# creates rop filenames dynamically from an HDA dirpath and filename field
def set_usd_filename():
    this = hou.node('.')
    rObj = hou.node(this.parm('obj').eval())
    
    rawDir = rObj.parm('model_dir').eval()
    rawFile = rObj.parm('model_file').eval()
    
    hou.node('./rop/alembic1').parm('filename').set(rawDir+'alembic/'+rawFile+'.abc')
    hou.node('./rop/usdoutput1').parm('usdfile').set(rawDir+'usd/'+rawFile+'.usda')
    hou.node('./rop/gltf1').parm('file').set(rawDir+'gltf/'+rawFile+'.glb')
    
# should create a new material with passed in properties
def newMaterial(stage, path, dclr, roughness, metallic, eclr=(0,0,0), opacity=1.0, ior=1.5, clearcoat=0.0, clearroug=0.0, occlusion=0.0):
    # TODO: keep adding more support, missing textures for now
    material = UsdShade.Material.Define(stage, path)
    pbrShader = UsdShade.Shader.Define(stage, path + '/PBRShader')

    pbrShader.CreateIdAttr("UsdPreviewSurface")
    pbrShader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set(dclr)
    pbrShader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(roughness)
    pbrShader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(metallic)
    pbrShader.CreateInput("emissiveColor", Sdf.ValueTypeNames.Color3f).Set(eclr)
    pbrShader.CreateInput("opacity", Sdf.ValueTypeNames.Float).Set(opacity)
    pbrShader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(ior)
    pbrShader.CreateInput("clearcoat", Sdf.ValueTypeNames.Float).Set(clearcoat)
    pbrShader.CreateInput("clearcoatRoughness", Sdf.ValueTypeNames.Float).Set(clearroug)

    material.CreateSurfaceOutput().ConnectToSource(pbrShader, "surface")

    return

def newMaterialViaShop(shopshader, stage, path):
    diffSet = False
    material = UsdShade.Material.Define(stage, path)
    uvInput = material.CreateInput('frame:stPrimvarName', Sdf.ValueTypeNames.Token)
    uvInput.Set('st')

    pbrShader = UsdShade.Shader.Define(stage, path + '/PBRShader')
    pbrShader.CreateIdAttr('UsdPreviewSurface')
    
    uvReader = UsdShade.Shader.Define(stage, path + '/uvReader')
    uvReader.CreateIdAttr('UsdPrimvarReader_float2')
    uvReader.CreateInput('varname', Sdf.ValueTypeNames.Token).ConnectToSource(uvInput)
    uvReader.CreateOutput('result', Sdf.ValueTypeNames.Float2)

    inputs = shopshader.inputConnections()
    for nodeInput in inputs:
        if nodeInput.outputName() == 'diffuseColor':
            inNode = nodeInput.inputNode()
            # create texture sampler node
            textureSampler = UsdShade.Shader.Define(stage, path + '/diffuseTexture')
            textureSampler.CreateIdAttr('UsdUVTexture')
            textureSampler.CreateInput('file', Sdf.ValueTypeNames.Asset).Set(inNode.parm('file').eval())
            textureSampler.CreateInput('uv', Sdf.ValueTypeNames.Float2).ConnectToSource(uvReader, 'result')
            textureSampler.CreateOutput('rgb', Sdf.ValueTypeNames.Float3)
        
            pbrShader.CreateInput('diffuseColor', Sdf.ValueTypeNames.Color3f).ConnectToSource(textureSampler, 'rgb')
            
            diffSet = True
            
    if not diffSet:
        dclr = Gf.Vec3f(shopshader.parmTuple('diffuseColor')[0].eval(), shopshader.parmTuple('diffuseColor')[1].eval(), shopshader.parmTuple('diffuseColor')[2].eval())
        pbrShader.CreateInput('diffuseColor', Sdf.ValueTypeNames.Color3f).Set(dclr)
        
    roughness = shopshader.parm('roughness').eval()
    metallic = shopshader.parm('metallic').eval()
    eclr = Gf.Vec3f(shopshader.parmTuple('emissiveColor')[0].eval(), shopshader.parmTuple('emissiveColor')[1].eval(), shopshader.parmTuple('emissiveColor')[2].eval())
    opacity = shopshader.parmTuple('opacity')[0].eval()
    ior = shopshader.parm('ior').eval()
    clearcoat = shopshader.parm('clearcoat').eval()
    clearroug = shopshader.parm('clearcoatRoughness').eval()
    occlusion = shopshader.parm('occlusion').eval()

    pbrShader.CreateInput('roughness', Sdf.ValueTypeNames.Float).Set(roughness)
    pbrShader.CreateInput('metallic', Sdf.ValueTypeNames.Float).Set(metallic)
    pbrShader.CreateInput('emissiveColor', Sdf.ValueTypeNames.Color3f).Set(eclr)
    pbrShader.CreateInput('opacity', Sdf.ValueTypeNames.Float).Set(opacity)
    pbrShader.CreateInput('ior', Sdf.ValueTypeNames.Float).Set(ior)
    pbrShader.CreateInput('clearcoat', Sdf.ValueTypeNames.Float).Set(clearcoat)
    pbrShader.CreateInput('clearcoatRoughness', Sdf.ValueTypeNames.Float).Set(clearroug)
    pbrShader.CreateInput('occlusion', Sdf.ValueTypeNames.Float).Set(occlusion)
    
    material.CreateSurfaceOutput().ConnectToSource(pbrShader, 'surface')

    return
    
def editMaterial(stage, matpath, dclr, roughness, metallic):
    
    #material = stage.GetPrimAtPath(matpath)
    material = UsdShade.Material.Get(stage, matpath)
    pbrShader = UsdShade.Shader.Define(stage, matpath + '/PBRShader')
    pbrShader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set(dclr)
    pbrShader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(roughness)
    pbrShader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(metallic)
    pbrShader.CreateInput("emissiveColor", Sdf.ValueTypeNames.Color3f).Set(eclr)
    pbrShader.CreateInput("opacity", Sdf.ValueTypeNames.Float).Set(opacity)
    pbrShader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(ior)
    pbrShader.CreateInput("clearcoat", Sdf.ValueTypeNames.Float).Set(clearcoat)
    pbrShader.CreateInput("clearcoatRoughness", Sdf.ValueTypeNames.Float).Set(clearroug)

    material.CreateSurfaceOutput().ConnectToSource(pbrShader, "surface")
    

def bindMaterial(stage, geopath, matpath):
    geo = stage.GetPrimAtPath(geopath)
    if not geo: # if prim is not valid, let's create a new over prim
        geo = stage.OverridePrim(geopath)
    
    material = UsdShade.Material.Get(stage, matpath)
    UsdShade.MaterialBindingAPI(geo).Bind(material)

# As a post script after a USD ROP this will write shading information to a _shade
# usd, and write a combined reference usd for geo and shading
def write_preview_shading():
    geoPaths = []
    this = hou.node('../../')
    rObj = hou.node(this.parm('obj').eval())
    pxrMatPaths = []

    rawDir = rObj.parm('model_dir').eval()
    rawFile = rObj.parm('model_file').eval()
        
    if(rawFile != None):
        filename = rawDir +'usd/' + rawFile
        # we get all the unique paths as these are the prim paths in our USD file
        # if we find a unique path we also try to grab the shopmaterialpath, we'll
        # create and bind materials from these
        packNode = this.node('PACK_FOR_SHADERS')
        
        for prim in packNode.geometry().prims():
            gpath = prim.attribValue('path')
            if gpath is not '':
                if gpath not in geoPaths:
                    gmat = prim.attribValue('shop_materialpath')
                    geoPaths.append((gpath,gmat))
        
        # now we follow the material links building up shaders, if we've already built
        # the shader then we bind the existing one
        stage = Usd.Stage.CreateNew(filename + '_shade.usda')
        for gpath in geoPaths:
            matName = gpath[1].rsplit('/')[-1]
            if matName is not '':
                sshader = hou.node(gpath[1])
                
                if sshader:        
                    matPath = '/Materials/' + matName
                    if matPath not in pxrMatPaths:
                        pxrMatPaths.append(matPath)
                        #newMaterial(shopShader, stage, matPath, Gf.Vec3f(0.73938,0.742392,0.72749), 0.336918, 0)
                        newMaterialViaShop(sshader, stage, matPath)
                        bindMaterial(stage, gpath[0], matPath)
                    else:
                        bindMaterial(stage, gpath[0], matPath)
        
        #editMaterial(stage, '/Materials/white_veneer')        

        # Let's write out our shading layer
        stage.Export(filename + '_shade.usda')

# As a post/pre script in a shell rop that can write a usdz as the final rop in
# a chain, it will then remove the composite files
def write_arkit_usdz():
    this = hou.node('../../')
    rObj = hou.node(this.parm('obj').eval())
    
    rawDir = rObj.parm('model_dir').eval()
    rawFile = rObj.parm('model_file').eval()
        
    if(rawFile != None):
        filename = rawDir +'usd/' + rawFile
        
        # Let's write out our combined usd that layers the geo with the shading
        stage = Usd.Stage.CreateNew(filename + '.usda')
        
        if this.parm('trange').eval() > 0:
            stage.SetStartTimeCode(this.parm('f1').eval())
            stage.SetEndTimeCode(this.parm('f2').eval())

        rootLayer = stage.GetRootLayer()
        #Sdf.Layer.CreateNew(filename + '_shade.usda')
        #print 'Creating new layer ' + filename + '_shade.usda'
        #Sdf.Layer.CreateNew(filename + '_geo.usdc')
        #print 'Creating new layer ' + filename + '_geo.usdc'
        rootLayer.subLayerPaths.append(filename + '_shade.usda')
        rootLayer.subLayerPaths.append(filename + '_geo.usdc')
        #usdPrim = stage.DefinePrim('/'+rawFile)
        
        #usdPrim.GetReferences().AddReference(filename + '_geo.usdc')
        #usdPrim.GetReferences().AddReference(filename + '_shade.usda')
        
        stage.Export(filename + '.usda')
        #stage.Export(filename + '.usdc')

        # CreateNewARKitUsdzPackage works with relative pathing, so we need to change our directory path to
        # the exported shaded usd path to sucessfully pull this together                
        os.chdir(rawDir + '/usd')
        UsdUtils.CreateNewARKitUsdzPackage(rawFile + '.usda', rawFile + '.usdz')
        
        # remove files that compositied together the usdz
        # os.remove(rawFile + '_shade.usda')
        # os.remove(rawFile + '_geo.usdc')
        # os.remove(rawFile + '.usda')
        # os.remove(rawFile + '.usdc')